name: rocksdb
on:
  push:
    branches:
      - master

permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run rocksdb
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
      - name: Run build
        run: ./build_rocksdb.sh
      - name: Run benchmark
        run: ./run_rocksdb.sh
      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: rocksdb
          tool: 'go'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '200%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@orca-zhang'